In [3]:
ord('a')

97

In [4]:
ord('b')

98

In [5]:
chr(98)

'b'

In [6]:
ord('z')

122

In [7]:
A = [10, 20, 30, 40, 50 ]

In [20]:
# if k==n:
#     return A

k = -2

A[-k:] + A[:-k]

[30, 40, 50, 10, 20]

In [10]:
A[-k:]

[40, 50]

In [11]:
A[:-k]

[10, 20, 30]

In [24]:
s = "the quick the the the the the brown fox jumps over the lazy little dog"

In [25]:
split_lst = s.split()
split_lst

['the',
 'quick',
 'the',
 'the',
 'the',
 'the',
 'the',
 'brown',
 'fox',
 'jumps',
 'over',
 'the',
 'lazy',
 'little',
 'dog']

In [28]:

set([(split_lst[i], split_lst[i+1]) for i in range(len(split_lst)-1)])

{('brown', 'fox'),
 ('fox', 'jumps'),
 ('jumps', 'over'),
 ('lazy', 'little'),
 ('little', 'dog'),
 ('over', 'the'),
 ('quick', 'the'),
 ('the', 'brown'),
 ('the', 'lazy'),
 ('the', 'quick'),
 ('the', 'the')}

In [32]:
import numpy as np

In [30]:
eles = [int(i) for i in "1 1 2 5 7 6 7 7 6 3".split()]
eles

[1, 1, 2, 5, 7, 6, 7, 7, 6, 3]

In [35]:
uniq, counts = np.unique(eles, return_counts=True )

In [37]:
uniq

array([1, 2, 3, 5, 6, 7])

In [38]:
counts

array([2, 1, 1, 1, 2, 3])

In [46]:
zeros = np.zeros(10, dtype='int')
zeros

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [45]:
uniq-1

array([0, 1, 2, 4, 5, 6])

In [42]:
zeros[uniq-1] = counts

In [44]:
zeros.astype('int')

array([2, 1, 1, 0, 1, 2, 3, 0, 0, 0])

In [48]:
A = np.arange(1,5)

In [52]:
denom = np.exp(A).sum()

In [54]:
np.exp(A)/denom

array([0.0320586 , 0.08714432, 0.23688282, 0.64391426])

In [58]:
A = np.array([1,0, 1, 0, 1, 1]).reshape(-1, 1)
B = np.array([0.4, 0.2, 0.91, 0.11, 0.86, 0.45]).reshape(-1, 1)

In [59]:
A

array([[1],
       [0],
       [1],
       [0],
       [1],
       [1]])

In [60]:
B

array([[0.4 ],
       [0.2 ],
       [0.91],
       [0.11],
       [0.86],
       [0.45]])

In [62]:
np.log(B)

array([[-0.91629073],
       [-1.60943791],
       [-0.09431068],
       [-2.20727491],
       [-0.15082289],
       [-0.7985077 ]])

In [67]:
partA = A*np.log(B)
partA

array([[-0.91629073],
       [-0.        ],
       [-0.09431068],
       [-0.        ],
       [-0.15082289],
       [-0.7985077 ]])

In [68]:
partB = (1-A)*np.log(1-B)
partB

array([[-0.        ],
       [-0.22314355],
       [-0.        ],
       [-0.11653382],
       [-0.        ],
       [-0.        ]])

In [72]:
-np.mean(partA + partB)

0.3832682274779855

In [74]:
a = np.zeros(27).reshape(3, 3, 3)
a

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [76]:
b = np.arange(9).reshape(3, 3)
b

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [77]:
a+b

array([[[0., 1., 2.],
        [3., 4., 5.],
        [6., 7., 8.]],

       [[0., 1., 2.],
        [3., 4., 5.],
        [6., 7., 8.]],

       [[0., 1., 2.],
        [3., 4., 5.],
        [6., 7., 8.]]])

In [78]:
a

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [81]:
a + b[np.newaxis, :, :]

array([[[0., 1., 2.],
        [3., 4., 5.],
        [6., 7., 8.]],

       [[0., 1., 2.],
        [3., 4., 5.],
        [6., 7., 8.]],

       [[0., 1., 2.],
        [3., 4., 5.],
        [6., 7., 8.]]])

In [82]:
b[np.newaxis, :, :].shape

(1, 3, 3)

In [84]:
import pandas as pd

In [85]:
df = pd.DataFrame({
 "A":['tst1','tst2','tst3','tst3'],
 "B":[5, 6, 7, 8],
 "C":[9, 10, 11 ,12],
 "D":[13, 14, 15, 16]
})

In [87]:
df.columns[1:]

Index(['B', 'C', 'D'], dtype='object')

In [88]:
np.array(df.columns)

array(['A', 'B', 'C', 'D'], dtype=object)

In [90]:
np.array(df.columns)

array(['A', 'B', 'C', 'D'], dtype=object)

In [94]:
df.melt(id_vars ='A', value_vars =['B', 'C', 'D'] ,var_name ='St_name', value_name ='Scores')

A St_name  Scores
0   tst1       B       5
1   tst2       B       6
2   tst3       B       7
3   tst3       B       8
4   tst1       C       9
5   tst2       C      10
6   tst3       C      11
7   tst3       C      12
8   tst1       D      13
9   tst2       D      14
10  tst3       D      15
11  tst3       D      16

In [96]:
df = pd.DataFrame({'Date':["2015-12-06", "2011-12-27", "2015-09-07", "2012-12-21", "2020-02-13", "2015-06-09"], 'RID':[498, 721, 375, 464, 813, 853], 'Phy':[22, 45, 1, 65, 22, 17], 'Chem':[52, 56, 32, 50, 24, 61], 'Math':[63, 37, 68, 62, 43 ,42]}) 


In [100]:
df['month'] = pd.to_datetime(df['Date']).dt.month

In [106]:
month = df['month'].value_counts().index[0]

In [107]:
month

12

In [110]:
df[df['month'] == month][['Phy', 'Chem', 'Math']].mean()

Phy     44.000000
Chem    52.666667
Math    54.000000
dtype: float64